package com.wislove.uc.entity;

import java.util.Date;

public class UserAccountBindInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.auth_id
     *
     * @mbggenerated
     */
    private String authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.auth_token
     *
     * @mbggenerated
     */
    private String authToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_bind_info.version_no
     *
     * @mbggenerated
     */
    private Integer versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.id
     *
     * @return the value of user_account_bind_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.id
     *
     * @param id the value for user_account_bind_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.user_id
     *
     * @return the value of user_account_bind_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.user_id
     *
     * @param userId the value for user_account_bind_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.type
     *
     * @return the value of user_account_bind_info.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.type
     *
     * @param type the value for user_account_bind_info.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.auth_id
     *
     * @return the value of user_account_bind_info.auth_id
     *
     * @mbggenerated
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.auth_id
     *
     * @param authId the value for user_account_bind_info.auth_id
     *
     * @mbggenerated
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.auth_token
     *
     * @return the value of user_account_bind_info.auth_token
     *
     * @mbggenerated
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.auth_token
     *
     * @param authToken the value for user_account_bind_info.auth_token
     *
     * @mbggenerated
     */
    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.update_time
     *
     * @return the value of user_account_bind_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.update_time
     *
     * @param updateTime the value for user_account_bind_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.create_time
     *
     * @return the value of user_account_bind_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.create_time
     *
     * @param createTime the value for user_account_bind_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_bind_info.version_no
     *
     * @return the value of user_account_bind_info.version_no
     *
     * @mbggenerated
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_bind_info.version_no
     *
     * @param versionNo the value for user_account_bind_info.version_no
     *
     * @mbggenerated
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
}